### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by MiNECRAFT-0** [Cheny233/Minecraft-AFK#4]
总是弹一个小窗口，无法放大，看起来好像是乱码 @Cheny233

**Comment by Cheny233** [comment]
感谢反馈，能够提供一下截图吗？

**Comment by SerinaNya** [comment]
> 总是弹一个小窗口，无法放大，看起来好像是乱码 @Cheny233

**在没有错误截图的情况下诊断任何问题，无异于闭眼开车！**

**Comment by MiNECRAFT-0** [comment]
有可能是我这边的问题，我部分程序也乱码，麻烦给个纠正乱码的方法


[url=http://www.mcbbs.net/thread-654082-1-1.html][img=320,64]https://t.cn/Aipqu0bv[/img][/url]



&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Cheny"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 晚上10:19
收件人:&nbsp;"Cheny233/Minecraft-AFK"<Minecraft-AFK@noreply.github.com&gt;;
抄送:&nbsp;"人民的名义"<2146633925@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Cheny233/Minecraft-AFK] 无法使用 (#4)





 
感谢反馈，能够提供一下截图吗？

**Comment by Cheny233** [comment]
对不起，你发送的链接我无法打开，能够在发送一次吗？

**Comment by Cheny233** [comment]
> 有可能是我这边的问题，我部分程序也乱码，麻烦给个纠正乱码的方法 [url=[http://www.mcbbs.net/thread-654082-1-1.html][img=320,64]https://t.cn/Aipqu0bv[/img][/url](http://www.mcbbs.net/thread-654082-1-1.html%5D%5Bimg=320,64%5Dhttps://t.cn/Aipqu0bv%5B/img%5D%5B/url)] &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Cheny"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月27日(星期五) 晚上10:19 收件人:&nbsp;"Cheny233/Minecraft-AFK"<Minecraft-AFK@noreply.github.com&gt;; 抄送:&nbsp;"人民的名义"<2146633925@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [Cheny233/Minecraft-AFK] 无法使用 (#4) 感谢反馈，能够提供一下截图吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好在吗，你发送的链接我无法打开，能够再发送一次吗？

**Comment by MiNECRAFT-0** [comment]
目前就是这样的
&nbsp;

[url=http://www.mcbbs.net/thread-654082-1-1.html][img=320,64]https://t.cn/Aipqu0bv[/img][/url]



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Cheny"<notifications@github.com&gt;; 
发送时间: 2020年3月28日(星期六) 上午8:59
收件人: "Cheny233/Minecraft-AFK"<Minecraft-AFK@noreply.github.com&gt;; 
抄送: "人民的名义"<2146633925@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Cheny233/Minecraft-AFK] 无法使用 (#4)





  
有可能是我这边的问题，我部分程序也乱码，麻烦给个纠正乱码的方法 [url=[http://www.mcbbs.net/thread-654082-1-1.html][img=320,64]https://t.cn/Aipqu0bv[/img]/url] &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Cheny"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月27日(星期五) 晚上10:19 收件人:&nbsp;"Cheny233/Minecraft-AFK"<Minecraft-AFK@noreply.github.com&gt;; 抄送:&nbsp;"人民的名义"<2146633925@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [Cheny233/Minecraft-AFK] 无法使用 (#4) 感谢反馈，能够提供一下截图吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你好在吗，你发送的链接我无法打开，能够再发送一次吗？

**Comment by CharlieYu4994** [comment]
您可以再他的mcbbs上发这张图片，不要链接，我用梯子都看不到。

**Comment by SerinaNya** [comment]
宁好，请在 GitHub Issues 中使用 Markdown 语法
