### ISSUE TITLE
希望有的新功能

### ISSUE THREAD

**Issue by trytodupe** [Cheny233/Minecraft-AFK#5]
这些功能的确不错，但是在有的服务器挂机钓鱼还是会被踢。
希望加个能转头的功能
:D

**Comment by SerinaNya** [comment]
转头能用的话也得在 `1.12.2 -`，因为海洋更新使得视角追随鼠标移动的机制发生巨大变化。
但是我们还没有读懂 Mojang 的源码，所以不会算转个头需要鼠标移动多少距离。。。。

**Comment by SerinaNya** [comment]
> 这些功能的确不错，但是在有的服务器挂机钓鱼还是会被踢。

被踢那也没办法。。。

**Comment by Cheny233** [comment]
> 这些功能的确不错，但是在有的服务器挂机钓鱼还是会被踢。
> 希望加个能转头的功能
> :D

转头功能目前在测试（咕咕咕）

**Comment by Cheny233** [comment]
> 这些功能的确不错，但是在有的服务器挂机钓鱼还是会被踢。
> 希望加个能转头的功能
> :D

服务器挂机钓鱼被踢不是我的程序问题，是服务器问题，有些服务器长时间不动就是会踢的

**Comment by SerinaNya** [comment]
> > 这些功能的确不错，但是在有的服务器挂机钓鱼还是会被踢。
> > 希望加个能转头的功能
> > :D
> 
> 服务器挂机钓鱼被踢不是我的程序问题，是服务器问题，有些服务器长时间不动就是会踢的

？不应该是反挂壁插件吗

**Comment by Cheny233** [comment]
> > > 这些功能的确不错，但是在有的服务器挂机钓鱼还是会被踢。
> > > 希望加个能转头的功能
> > > :D
> > 
> > 
> > 服务器挂机钓鱼被踢不是我的程序问题，是服务器问题，有些服务器长时间不动就是会踢的
> 
> ？不应该是反挂壁插件吗

差不多，反AFK

**Comment by CharlieYu4994** [comment]
**宁们不要轰炸咱的邮箱**

**Comment by trytodupe** [comment]
我要的转头只需要动1pixel也够了
比如先往左1pixiel 然后等十秒 往右1pixel

**Comment by SerinaNya** [comment]
> 比如先往左1pixiel 然后等十秒 往右1pixel

那还是得算时间，但是很高兴地告诉你，昨晚我们试验成功了，如果不咕咕咕的话，@Cheny233 会在今天有新的 commit 的。

**Comment by CharlieYu4994** [comment]
我们的Python版本在搞定配置文件读取后就会加入完美的鼠标移动

**Comment by SerinaNya** [comment]
<https://github.com/jinzhijie/py-Minecraft-AFK>

**Comment by trytodupe** [comment]
> 我们的Python版本在搞定配置文件读取后就会加入完美的鼠标移动

鼠标不在游戏里的时候也可以？

**Comment by SerinaNya** [comment]
> > 我们的Python版本在搞定配置文件读取后就会加入完美的鼠标移动
> 
> 鼠标不在游戏里的时候也可以？

昨天测下来好像可以

**Comment by Cheny233** [comment]
您们不要轰炸咱的邮箱了，一早起来……

**Comment by trytodupe** [comment]
> > > 我们的Python版本在搞定配置文件读取后就会加入完美的鼠标移动
> > 
> > 
> > 鼠标不在游戏里的时候也可以？
> 
> 昨天测下来好像可以

好 我去试试

**Comment by trytodupe** [comment]
> 您们不要轰炸咱的邮箱了，一早起来……

其实只要unwatch就好了

**Comment by SerinaNya** [comment]
> > > > 我们的Python版本在搞定配置文件读取后就会加入完美的鼠标移动
> > > 
> > > 
> > > 鼠标不在游戏里的时候也可以？
> > 
> > 
> > 昨天测下来好像可以
> 
> 好 我去试试

你没东西可试，还没有 push 代码

**Comment by CharlieYu4994** [comment]
> 您们不要轰炸咱的邮箱了，一早起来……

宁昨天也是这么对我的

**Comment by Cheny233** [comment]
> > 您们不要轰炸咱的邮箱了，一早起来……
> 
> 其实只要unwatch就好了

……我自己的项目啊

**Comment by SerinaNya** [comment]
> > 您们不要轰炸咱的邮箱了，一早起来……
> 
> 其实只要unwatch就好了

宁好，其实我们是一个开发组的

**Comment by Cheny233** [comment]
> > 您们不要轰炸咱的邮箱了，一早起来……
> 
> 宁昨天也是这么对我的

好了stop

**Comment by CharlieYu4994** [comment]
是的，虽然我很菜

**Comment by CharlieYu4994** [comment]
> > > 您们不要轰炸咱的邮箱了，一早起来……
> > 
> > 
> > 宁昨天也是这么对我的
> 
> 好了stop
绝不

**Comment by trytodupe** [comment]
开发自己吵起来了 这咋办嘛

**Comment by CharlieYu4994** [comment]
其实可以close了

**Comment by trytodupe** [comment]
RIP
